sudo: required
language: java
jdk: oraclejdk11

services:
  - docker

install: true

git:
  quiet: true
  
cache:
  directories:
  - $HOME/.m2

before_script:
  - cd $HOME
  - git clone -b release/0.2.1 --single-branch https://github.com/hashgraph/hedera-sdk-java.git
  - cd hedera-sdk-java
  - cd $TRAVIS_BUILD_DIR

script:
  - mvn clean install
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push payper/payper-gateway:latest

branches:
  only:
  - master
