sudo: false
language: java
jdk: oraclejdk11

install: true

git:
  quiet: true
  
cache:
  directories:
  - $HOME/.m2

services:
  - docker

before_script:
  - cd $HOME
  - git clone -b release/0.2.1 --single-branch https://github.com/hashgraph/hedera-sdk-java.git
  - cd hedera-sdk-java
  - mvn clean install
  - cd $TRAVIS_BUILD_DIR

jobs:
  include:
    - stage: build
      script:
        - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
        - mvn clean install
        - docker push payper/payper-gateway:latest

branches:
  only:
  - master
