logging.level.org.springframework: INFO
logging.level.com.hedera.sdk.node.HederaNode: WARN

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017
      database: payperdb
  profiles:

payper:
  baseUrl: ${BASE_URL:http://localhost:8080}
  redirectPath: 'pypr/payment-required'
  paymentOptions:
    - id: HEDERA_HBAR_INVOICE
      name: "Hedera Hashgraph"
      currency: HBAR
      currencyName: "HBar"
    - id: LIGHTNING_BTC
      name: "Bitcoin Lightning Network"
      currency: SATOSHI_BTC
      currencyName: "SATS"
    - id: DUMMY_COIN
      name: "Dummy Network"
      currency: DUMMY_COIN
      currencyName: "Dummy Coin"
